{
 "title": "floyd dash",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "USD exchange rate",
   "type": "timeseries",
   "description": "according to CNB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exchange_rates",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "currency::tag", "operator": "=", "value": "USD" }
     ]
    }
   ]
  },
  {
   "title": "BITCOIN",
   "type": "timeseries",
   "description": "Bitcoin price in USD over time according to Yahoo finance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cryptocurrencies",
     "query": "SELECT mean(\"value\") FROM \"cryptocurrencies\" WHERE (\"crypto\"::tag = 'bitcoin') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "crypto::tag", "operator": "=", "value": "bitcoin" }
     ]
    }
   ]
  },
  {
   "title": "CEZ",
   "type": "timeseries",
   "description": "CEZ stocks in CZK (Yfinance)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stocks",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "symbol::tag", "operator": "=", "value": "CEZ.PR" }
     ]
    }
   ]
  },
  {
   "title": "GOLD",
   "type": "timeseries",
   "description": "Gold price per 1 OZ according to Yahoo finance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "precious_metals",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "metal::tag", "operator": "=", "value": "gold" }
     ]
    }
   ]
  },
  {
   "title": "S&P 500",
   "type": "timeseries",
   "description": "Stocks in USD (Yahoo finance)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stocks",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "symbol::tag", "operator": "=", "value": "^GSPC" }
     ]
    }
   ]
  },
  {
   "title": "SILVER",
   "type": "timeseries",
   "description": "Silver prizes per OZ T according to yahoo finance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "precious_metals",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "metal::tag", "operator": "=", "value": "silver" }
     ]
    }
   ]
  },
  {
   "title": "ETHEREUM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cryptocurrencies",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "crypto::tag", "operator": "=", "value": "ethereum" }
     ]
    }
   ]
  }
 ]
}